# Generated by Django 6.0.3 on 2026-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('recue', 'Reçue'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='brouillon', max_length=10)),
                ('devise', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('frais_approche', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_attendue', models.DateField(blank=True, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement inventaire'), ('rebut', 'Rebut / Casse'), ('inventaire', 'Inventaire')], max_length=15)),
                ('quantite', models.IntegerField()),
                ('stock_avant', models.IntegerField()),
                ('stock_apres', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='N° commande, bon de livraison, etc.', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('nom_en', models.CharField(blank=True, max_length=200)),
                ('categorie', models.CharField(choices=[('alcools', 'Alcools'), ('parfums', 'Parfums'), ('tabac', 'Tabac'), ('cosmetiques', 'Cosmétiques'), ('confiserie', 'Confiserie'), ('accessoires', 'Accessoires'), ('alimentaire', 'Alimentaire')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('prix_xof', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_eur', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, help_text='0 pour Duty Free', max_digits=5)),
                ('stock', models.IntegerField(default=0)),
                ('stock_min', models.IntegerField(default=5, help_text="Seuil d'alerte")),
                ('stock_max', models.IntegerField(default=100)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Sommier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('reference_djbc', models.CharField(blank=True, max_length=100)),
                ('quantite_initiale', models.IntegerField()),
                ('quantite_entree', models.IntegerField(default=0)),
                ('quantite_sortie', models.IntegerField(default=0)),
                ('date_ouverture', models.DateField()),
                ('date_apurement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_cours', "En cours d'apurement"), ('apure', 'Apuré')], default='actif', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sommier DJBC',
                'ordering': ['-date_ouverture'],
            },
        ),
    ]
