# Generated by Django 6.0.3 on 2026-03-12 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=20, unique=True)),
                ('numero_caisse', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('annulee', 'Annulée'), ('suspendue', 'Suspendue')], default='payee', max_length=10)),
                ('devise', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remise_totale', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('passager_nom', models.CharField(blank=True, max_length=200)),
                ('vol_reference', models.CharField(blank=True, max_length=50)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('synced', models.BooleanField(default=True)),
                ('date_locale', models.DateTimeField(help_text='Date réelle de la vente (important pour mode offline)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'ordering': ['-date_locale'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], max_length=15)),
                ('devise', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('montant_xof', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monnaie_rendue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taux_change', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
            },
        ),
        migrations.CreateModel(
            name='DonneesPassagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('nombre_passagers', models.IntegerField()),
                ('source', models.CharField(default='Aéroport Ouagadougou', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Données passagers',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['date_locale'], name='ventes_vent_date_lo_575c76_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['caissier'], name='ventes_vent_caissie_308f46_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut'], name='ventes_vent_statut_4c1c73_idx'),
        ),
    ]
