# Generated by Django 4.2.7 on 2026-03-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fidelite", "0001_initial"),
        ("ventes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="carte_fidelite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventes",
                to="fidelite.cartefidelite",
            ),
        ),
    ]
