# Generated by Django 6.0.3 on 2026-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(default='DJBC Duty Free Ouagadougou', max_length=200)),
                ('nif', models.CharField(default='BF-2024-00123456', max_length=50)),
                ('adresse', models.CharField(default='Aéroport International de Ouagadougou', max_length=300)),
                ('telephone', models.CharField(default='+226 25 30 65 00', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('taux_eur_xof', models.DecimalField(decimal_places=4, default=655.957, max_digits=10)),
                ('taux_usd_xof', models.DecimalField(decimal_places=4, default=607.5, max_digits=10)),
                ('msg_accueil_1', models.CharField(default='Bienvenue — Welcome', max_length=200)),
                ('msg_accueil_2', models.CharField(default='Zone de transit international', max_length=200)),
                ('msg_politesse', models.CharField(default='Merci. Bon voyage — Thank you. Safe travels.', max_length=200)),
                ('seuil_alerte_stock', models.PositiveIntegerField(default=10)),
                ('delai_apurement_sommier', models.PositiveIntegerField(default=30)),
                ('points_par_xof', models.DecimalField(decimal_places=4, default=0.001, help_text='Points gagnés par XOF dépensé', max_digits=6)),
                ('valeur_point_xof', models.DecimalField(decimal_places=2, default=5, help_text="Valeur d'un point en XOF", max_digits=8)),
                ('seuil_fidelite_bronze', models.PositiveIntegerField(default=100)),
                ('seuil_fidelite_silver', models.PositiveIntegerField(default=500)),
                ('seuil_fidelite_gold', models.PositiveIntegerField(default=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
