# Generated by Django 6.0.3 on 2026-03-13 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('niveau', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_visite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carte de fidélité',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='MouvementFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('gain', 'Gain points'), ('utilisation', 'Utilisation points'), ('ajustement', 'Ajustement manuel'), ('expiration', 'Expiration')], max_length=20)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_vente', models.CharField(blank=True, max_length=50)),
                ('montant_achat_xof', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='fidelite.cartefidelite')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
